# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /
    controller: App\Controller\LuckyController::number
    
form_formation:
    path: /formation/create
    controller: App\Controller\FormationController::create

form_formation_edit:
    path: /formation/edit/{id}
    controller: App\Controller\FormationController::edit

valid_formation:
    path: /formation/valid/
    controller: App\Controller\FormationController::valid
    
    
    
form_experience:
    path: /experience/create
    controller: App\Controller\ExperienceController::create

form_experience_edit:
    path: /experience/edit/{id}
    controller: App\Controller\ExperienceController::edit

valid_experience:
    path: /experience/valid
    controller: App\Controller\ExperienceController::valid
    
form_experience_delete:
    path: /experience/delete/{id}
    controller: App\Controller\ExperienceController::delete
    
    
    
form_competences:
    path: /competences/create
    controller: App\Controller\CompetencesController::create

form_competences_edit:
    path: /competences/edit/{id}
    controller: App\Controller\CompetencesController::edit

valid_competences:
    path: /competences/valid
    controller: App\Controller\CompetencesController::valid
    
    
    
form_profil:
    path: /profil/create
    controller: App\Controller\ProfilController::create

form_profil_edit:
    path: /profil/edit/{id}
    controller: App\Controller\ProfilController::edit

valid_profil:
    path: /profil/valid
    controller: App\Controller\ProfilController::valid
    
admin:
    path: /admin
    controller: App\Controller\LuckyController::admin
